CREATE DATABASE test;
USE test;

DROP FUNCTION IF EXISTS temp_func;
DELIMITER //
CREATE FUNCTION temp_func()
  RETURNS INTEGER READS SQL DATA
BEGIN
  RETURN 3;
END //
DELIMITER ;

DROP PROCEDURE IF EXISTS temp_proc;
DELIMITER //
CREATE PROCEDURE temp_proc()
BEGIN
  CREATE TEMPORARY TABLE temp_table AS SELECT 1;

  INSERT INTO temp_table SELECT temp_func();
END //
DELIMITER ;

CALL temp_proc();
